# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f30d73ac7847d600af121b5455db1279fbf4709894294fa5dd349b28124cfe2663f6a1826e1f54c1a45db3a53ff076455c50829df69a2c3cc039ae3e84ca51

test:
  secret_key_base: d2518b2e4ce3b9a225bd321a6014b6e7b9371ba691f4771c614b900a25b58c0fd0b35ad525c4ea97b86aaf261cb540c38c7f93b2205333b99335bcaecca67a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
